export const CHANGE_TEXT = 'CHANGE_TEXT';
export const CHANGE_FONT_FAMILY = 'CHANGE_FONT_FAMILY';
export const CHANGE_FONT_COLOR = 'CHANGE_FONT_COLOR';
export const CHANGE_FONT_SIZE = 'CHANGE_FONT_SIZE';
export const BG_CHANGE_IMAGE = 'BG_CHANGE_IMAGE';
export const CHANGE_TEXT_ALIGN = 'CHANGE_TEXT_ALIGN';
export const ADD_NEW_TEXT = 'ADD_NEW_TEXT';
export const ADD_IMAGE_URL = 'ADD_IMAGE_URL';
export const CHANGE_POSITION = 'CHANGE_POSITION';
export const REMOVE_OPTION = 'REMOVE_OPTION';
export const ACTIVATE_OPTION = 'ACTIVATE_OPTION';

